cluster_name: cluster-cveiga-01
configmap: us-east-1-cluster-cveiga-01-config
data:
  ACM_VERSION: '2.14'
  KUBERNETES_VERSION: '1.33'
  PROVISION_APPLICATION_PATH: providers/aws/provision-application
  PROVISION_PATH: providers/aws/provision
  PROVISION_REPO: https://github.com/cristianoveiga/regionality.git
  PROVISION_REVISION: prerender-configmaps
  REGION: us-east-1
  ROLE_ARN: arn:aws:iam::100000000001:role/central-control-plane
  TESTVAL: regval
  WORKER_MACHINE_COUNT: '1'
  WORKER_MACHINE_TYPE: t4g.medium
name: cluster-cveiga-01
region: us-east-1
sector: canary
tasks:
  post-task-git-url: https://github.com/cristianoveiga/regionality.git
  post-task-path: providers/aws/pipeline-tasks/post.yaml
  post-task-revision: prerender-configmaps
  pre-task-git-url: https://github.com/cristianoveiga/regionality.git
  pre-task-path: providers/aws/pipeline-tasks/pre.yaml
  pre-task-revision: prerender-configmaps
  provision-task-git-url: https://github.com/cristianoveiga/regionality.git
  provision-task-path: providers/aws/pipeline-tasks/provision.yaml
  provision-task-revision: prerender-configmaps
